config/routes.rb
Rails.application.routes.draw do
  post 'filter/show'

  post 'transaction_on_accounts/index'
  get 'transaction_on_accounts/new'

  get 'transaction_on_accounts/show'

  get 'transaction_on_accounts/create'

  get 'user_login/index'
  get 'account/index'
 

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { :sessions => "my_sessions" }
  resources :users
  resources :accounts do
  	resources :transaction_on_accounts
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transaction_on_account

  validates :name, presence: true
  validates :critic_value, presence: true
  validates :notifications, presence: true
 
 def critic
   if ((transaction_on_account.sum(:value) < critic_value) and notifications)
      # debugger  
      # NotifyMailer.sample_email(user).deliver
   end
 end 
  
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: "from@example.com"
  layout 'mailer'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account
  belongs_to :category
end

app/models/transaction_on_account.rb
require 'filewatcher'
class TransactionOnAccount < ActiveRecord::Base 
 belongs_to :account
  belongs_to :category
  after_create :check
  validates :category, presence: true
  validates :value, presence: true
  validates :reason, presence: true
  validates :date, presence: true

  def check
     account.critic 
  end
 
 # FileWatcher.new(["/Users/user/Documents/My docs/RoR/Projects/inno/xml"]).watch() do |filename, event|
 #    if(event == :changed)
 #      puts "File updated: " + filename
 #    end
 #    if(event == :delete)
 #      puts "File deleted: " + filename
 #    end
 #    if(event == :new)
 #      debugger
 #      puts "Added file: " + filename
 #    end
 # end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :stalkable
  has_many :accounts
  has_many :logins, class_name: 'UserLogin'
  
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
  belongs_to :User
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
   before_action :authenticate_user!


   def new

   end

   def index
     @account = Account.new
     @accounts = current_user.accounts
   end

   def create
     @account = Account.new(param.merge(user_id: current_user.id))
     @account.save 
     redirect_to :back
   end

   def update
     @account = Account.find(params[:id])
     @account.update_attributes(param)
     redirect_to @account
   end

   def show
    @account = current_user.accounts.find(params[:id]) 
   end

   private
     def param
       params.require(:account).permit(:name, :notifications, :critic_value)
     end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_concurrent_session
    if duplicate_session?
      sign_out_and_redirect(current_user)
      flash[:notice] = "Duplicate Login Detected"
    end
  end

  def duplicate_session?
   debugger 
   user_signed_in? && (current_user.token != session[:token])
  end
end

app/controllers/filter_controller.rb
class FilterController < ApplicationController
  def show
    debugger
  end
end

app/controllers/my_sessions_controller.rb
class MySessionsController < Devise::SessionsController
  skip_before_filter :check_concurrent_session

  def create
    super
    set_login_token
  end

  private
  def set_login_token
    token = Devise.friendly_token
    session[:token] = token
    current_user.token = token
    current_user.save(validate: false)
  end
end

app/controllers/user_login_controller.rb
class UserLoginController < ApplicationController
  def index
     @user_logins = current_user.logins
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagory_helper.rb
module CatagoryHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/transaction_on_accounts_helper.rb
module TransactionOnAccountsHelper
end

app/helpers/user_login_helper.rb
module UserLoginHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li> <%= link_to "History", user_login_index_path %></li>
  <li> <%= link_to "Accounts", accounts_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inno" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Inno" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
Continue with signing in or sign up if you have not been registered yet !
</p>