config/routes.rb
Rails.application.routes.draw do
  post 'filter/show'

  post 'transaction_on_accounts/index'
  get 'transaction_on_accounts/new'

  get 'transaction_on_accounts/show'

  get 'transaction_on_accounts/create'

  get 'user_login/index'
  get 'account/index'
 

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { :sessions => "my_sessions" }
  resources :users
  resources :accounts do
  	resources :transaction_on_accounts
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transaction_on_account

  validates :name, presence: true
  validates :critic_value, presence: true
  validates :notifications, presence: true
 
 def critic
   if ((transaction_on_account.sum(:value) < critic_value) and notifications)
      # debugger  
      # NotifyMailer.sample_email(user).deliver
   end
 end 
  
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: "from@example.com"
  layout 'mailer'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account
  belongs_to :category
end

app/models/transaction_on_account.rb
require 'filewatcher'
class TransactionOnAccount < ActiveRecord::Base 
 belongs_to :account
  belongs_to :category
  after_create :check
  validates :category, presence: true
  validates :value, presence: true
  validates :reason, presence: true
  validates :date, presence: true

  def check
     account.critic 
  end
 
 # FileWatcher.new(["/Users/user/Documents/My docs/RoR/Projects/inno/xml"]).watch() do |filename, event|
 #    if(event == :changed)
 #      puts "File updated: " + filename
 #    end
 #    if(event == :delete)
 #      puts "File deleted: " + filename
 #    end
 #    if(event == :new)
 #      debugger
 #      puts "Added file: " + filename
 #    end
 # end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :stalkable
  has_many :accounts
  has_many :logins, class_name: 'UserLogin'
  
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
  belongs_to :User
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
   before_action :authenticate_user!


   def new

   end

   def index
     @account = Account.new
     @accounts = current_user.accounts
   end

   def create
     @account = Account.new(param.merge(user_id: current_user.id))
     @account.save 
     redirect_to :back
   end

   def update
     @account = Account.find(params[:id])
     @account.update_attributes(param)
     redirect_to @account
   end

   def show
    @account = current_user.accounts.find(params[:id]) 
   end

   private
     def param
       params.require(:account).permit(:name, :notifications, :critic_value)
     end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_concurrent_session
    if duplicate_session?
      sign_out_and_redirect(current_user)
      flash[:notice] = "Duplicate Login Detected"
    end
  end

  def duplicate_session?
   debugger 
   user_signed_in? && (current_user.token != session[:token])
  end
end

app/controllers/filter_controller.rb
class FilterController < ApplicationController
  def show
    debugger
  end
end

app/controllers/my_sessions_controller.rb
class MySessionsController < Devise::SessionsController
  skip_before_filter :check_concurrent_session

  def create
    super
    set_login_token
  end

  private
  def set_login_token
    token = Devise.friendly_token
    session[:token] = token
    current_user.token = token
    current_user.save(validate: false)
  end
end

app/controllers/transaction_on_accounts_controller.rb
class TransactionOnAccountsController < ApplicationController
   
  def index
  end

  def new
  end

  def show
  end

  def create
	cat = Category.find_by(name: params[:transaction_on_account][:category])
        if cat.nil?
           cat = Category.new(name: params[:transaction_on_account][:category]) if cat.nil?
           cat.save 
        end
         
        @actual_transaction = TransactionOnAccount.new(params_t.merge(account_id: params[:account_id], category: cat))
	@actual_transaction.save

        redirect_to @account = current_user.accounts.find(params[:account_id])        

  end

  private
   
   def params_t
    params.require(:transaction_on_account).permit(:value, :reason, :date, :category)
  end
end

app/controllers/user_login_controller.rb
class UserLoginController < ApplicationController
  def index
     @user_logins = current_user.logins
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagory_helper.rb
module CatagoryHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/transaction_on_accounts_helper.rb
module TransactionOnAccountsHelper
end

app/helpers/user_login_helper.rb
module UserLoginHelper
end

app/views/accounts/index.html.erb
<h1 style="text-align:center;">ACCOUNTS</h1>
<table class="table table-hover"  data-toggle="table">
      <thead>
         <tr>
              <th data-sortable="true">Name</th>
              <th data-sortable="true">Critic Value</th>
              <th data-sortable="true">Notification</th>
              <th>Actual value</th>
         </tr>
      </thead>
      <tbody>
      <% @accounts.each do |ac| %>
          <tr>
            <td><%= link_to "#{ac.name}", ac %></td>
            <td><%= ac.critic_value %></td>
            <td><%= ac.notifications ? true : false %></td>
            <td><%= ac.transaction_on_account.sum(:value)%></td> 
         </tr>
      <% end %>
      </tbody>
    </table>
<h2>Add new Account</h2>
    <%= simple_form_for @account do |f| %>
        <%= f.input :name %>
        <%= f.input :critic_value %>
        <%= f.input :notifications, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.button :submit%>
    <% end %>
  </div>

app/views/accounts/show.html.erb
<h1 style="text-align:center;">Actual Account</h1>
<h3 style="text-align:center;">Overall value: <%= @account.transaction_on_account.sum(:value) %></h3>
<% if @account.transaction_on_account.sum(:value) < @account.critic_value %>
   <h2 style="text-align: center; color: red;">CRITICAL VALUE RAISED</h2>
<% end %>
    <%= simple_form_for(@account) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :notifications %>
      <%= f.check_box :notifications, class: 'form-control' %>
      <%= f.label :critic_value %>
      <%= f.text_field :critic_value, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

<div style="margin-top: 50px; margin-bottom: 50px;" class="row">
<table  class="table table-hover"  data-toggle="table">
      <thead>
         <tr>
              <th data-sortable="true">Category</th>
              <th data-sortable="true">Value</th>
              <th data-sortable="true">Reason</th>
              <th data-sortable="true">Time</th>
         </tr>
      </thead>
      <tbody>
      <% @account.transaction_on_account.each do |tr| %>
          <tr>
            <td><%= tr.category.name %></td>
	    <td><%= tr.value %></td>
            <td><%= tr.reason %></td>
            <td><%= tr.date %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>

<%= simple_form_for @actual_transaction=TransactionOnAccount.new, :url => account_transaction_on_accounts_path(@account, @actual_transaction) do |f| %>
 <h3 style="text-align: center;">Add Transaction</h3>
        <div class="form-group">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :value %>
          <%= f.number_field :value, class: 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :reason %>
          <%= f.text_field :reason, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.input :date, :as => :datetime_picker, class: 'form-control', :required => true, :label => 'Date field', input_html: {data: {date_options: {defaultDate: DateTime.now}}}  %>
        </div>
        <%= f.submit 'Add new transaction', :class => 'btn btn-success' %>
    <% end %>

app/views/filter/show.html.erb
<h1>Filter#show</h1>
<p>Find me in app/views/filter/show.html.erb</p>

app/views/transaction_on_accounts/create.html.erb
<h1>TransactionOnAccounts#create</h1>
<p>Find me in app/views/transaction_on_accounts/create.html.erb</p>

app/views/transaction_on_accounts/new.html.erb
<h1>TransactionOnAccounts#new</h1>
<p>Find me in app/views/transaction_on_accounts/new.html.erb</p>

app/views/transaction_on_accounts/show.html.erb
<h1>TransactionOnAccounts#show</h1>
<p>Find me in app/views/transaction_on_accounts/show.html.erb</p>

app/views/user_login/index.html.erb
<h1 style="text-align:center;">Session history</h1>
<table class="table table-hover">
  <thead>
    <tr>
        <th>IP address</th>
        <th>User agent</th>
        <th>Signed in</th>
        <th>Last seen</th>
        <th>Signed out</th>
    </tr>
  </thead>
  <tbody>
    <% @user_logins.each do |ul| %>
     <tr> 
          <td><%= ul.ip_address  %></td>
           <td><%= ul.user_agent  %></td>       
           <td><%= ul.signed_in_at  %></td>
           <td><%= ul.last_seen_at  %></td>
           <td><%= ul.signed_out_at  %></td>
     </tr>    
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">
<h1 style="text-align:center; margin-top: 30%; margin-bottom:30%">Financial system</h1>
</div>
<!-- /.container -->